steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", 
          "-t", 
          "europe-west1/${PROJECT_ID}/model-serve/trainer", 
          "-f",
          "trainer.dockerfile",
          ".", 
          "--build-arg",
          "WANDB_TOKEN=$$WANDB_TOKEN"]
    secretEnv: ["WANDB_TOKEN"]
  - name: "gcr.io/cloud-builders/docker"
    args: ['push', "europe-west1/${PROJECT_ID}/model-serve/trainer"]
availableSecrets:
  secretManager:
    - versionName: projects/422063201452/secrets/WANDB_MOESEN_TOKEN/versions/1
      env: "WANDB_TOKEN"
options:
  logging: CLOUD_LOGGING_ONLY