steps:
  - name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "europe-north1-a.pkg.dev/${PROJECT_ID}/docker-repo/trainer", "."]
  -name: "gcr.io/cloud-builders/docker"
  args: ['push', "gcr.io/${PROJECT_ID}/trainer"]