model:
  sep: " = /@\ = " 
  offset: 30

training:
  data_folder: data/processed/
  output_folder: models/exp1
  model: gpt2
  batch_size: 4
  lr: 5e-05
  epochs: 3
  max_steps: -1
  seed: 42
  fp16: True