name: "Run tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local\pip\Cache

    steps:
    - uses: actions/cache@v2
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
         ${{ runner.os }}-pip-
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Create folders (Windows)
      run: |
        mkdir data, data\raw, data\processed, data\external, data\interim
      if: matrix.os == 'windows-latest'
    - name: Create folders (non-Windows)
      run: |
        mkdir -p data data/raw data/processed data/external data/interim
      if: matrix.os != 'windows-latest'
    - name: Download data
      run: |
        python src/data/download_data.py data/raw
        python src/data/make_dataset.py data/raw data/processed
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v tests/
